name: Check features with Cucumber and push to CucumberStudio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo ${{ github.event.pull_request.title }}
    - run: npm test
      if: env.CS_PROJECT_ACCESS_TOKEN == null
      env:
          CS_PROJECT_ACCESS_TOKEN: ${{ secrets.CS_PROJECT_ACCESS_TOKEN }}
    - name: 'Run npm test and push results to CucumberStudio'
      if: env.CS_PROJECT_ACCESS_TOKEN != null
      run: npm run push-results
      env:
          CS_PROJECT_ACCESS_TOKEN: ${{ secrets.CS_PROJECT_ACCESS_TOKEN }}
          REPOSITORY_NAME: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_BRANCH: ${{ github.head_ref }}
          PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          TRY_SOMETHING_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
