name: Check features with Cucumber and push to CucumberStudio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - run: npm test
      if: env.CS_PROJECT_ACCESS_TOKEN == null
    - name: 'Run npm test and push results to CucumberStudio'
      if: env.CS_PROJECT_ACCESS_TOKEN != null
      run: npm run push-results
      env:
          CS_PROJECT_ACCESS_TOKEN: ${{ secrets.CS_PROJECT_ACCESS_TOKEN }}
          REPOSITORY_NAME: ${{ github.repository }}
          COMMIT_HASH: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
